version: "3"
services:
  node_backend:
    container_name: "node_backend"
    build: ./node_backend/
    ports:
      - "3001:3001"

  pg:
    image: "postgres:12"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg/db_data:/var/lib/postgresql/data
